"use client";
import { useEffect, useRef, useState } from "react";
type Circle = { id: string; name: string; owner_id: string };
type Details = { circle: Circle; members: Array<{ id: string; name: string }>; challenges: Array<{ id: string; week: string }>; results: Array<{ name: string; state: string; revision: number; best_rank: number | null }> };
export default function Circles() {
  const [session, setSession] = useState<{ guest: { id: string; name: string } | null; csrf?: string }>({ guest: null });
  const [circles, setCircles] = useState<Circle[]>([]); const [details, setDetails] = useState<Details | null>(null);
  const [name, setName] = useState(""); const [token, setToken] = useState(""); const [link, setLink] = useState("");
  const [guestName, setGuestName] = useState("");
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const lock = useRef(false);
  const createId = useRef<string | null>(null); const inviteToken = useRef<string | null>(null);
  async function api(path: string, body?: unknown) {
    const response = await fetch(path, body ? { method: "POST", headers: { "Content-Type": "application/json", "X-Braise-CSRF": session.csrf ?? "" }, body: JSON.stringify(body) } : { cache: "no-store" });
    const data = await response.json() as Details & { circles: Circle[]; guest: { id: string; name: string } | null; csrf?: string; id: string; circle_id: string; game: string; error?: string }; if (!response.ok) throw new Error(data.error ?? "Service indisponible."); return data;
  }
  async function perform(action: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Service indisponible."); } finally { lock.current = false; setBusy(false); } }
  async function refresh() { setCircles((await api("/api/circles")).circles); }
  async function open(id: string, challenge?: string) { setDetails(await api(`/api/circles?id=${id}${challenge ? `&challenge=${challenge}` : ""}`)); setLink(""); inviteToken.current = null; }
  useEffect(() => { const value = new URLSearchParams(location.hash.slice(1)).get("invitation"); if (value) { setToken(value); history.replaceState(null, "", location.pathname); } void perform(async () => { const data = await api("/api/session"); setSession(data); if (data.guest) await refresh(); });
  // Opening an invitation never consumes it or creates an identity.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return <main className="main-shell laboratory-shell"><a className="text-action" href="/">← Braise</a><div className="page-heading"><h1>Les cercles<span>.</span></h1></div><p>Un défi commun chaque semaine, des résultats réellement conservés. Les liens restent soumis à l’accès privé du Site.</p>
    {!session.guest ? <section className="collection-picker laboratory-card"><form onSubmit={event => { event.preventDefault(); void perform(async () => { setSession(await api("/api/session", { name: guestName })); await refresh(); }); }}><label htmlFor="circle-guest">Votre pseudonyme</label><input id="circle-guest" maxLength={24} value={guestName} disabled={busy} onChange={event => setGuestName(event.target.value)} /><button className="primary-button" disabled={busy || !guestName.trim()}>Créer mon identité et conserver cette invitation</button></form><p>Pour retrouver une identité existante, utilisez Votre espace puis rouvrez le lien d’invitation.</p><a href="/espace">Retrouver mon identité</a></section> : <>
      <section className="collection-picker laboratory-card"><h2>Mes cercles</h2>{circles.length === 0 && <p>Aucun cercle rejoint.</p>}{circles.map(circle => <button className="text-action" disabled={busy} key={circle.id} onClick={() => void perform(() => open(circle.id))}>{circle.name}</button>)}
      <form onSubmit={event => { event.preventDefault(); void perform(async () => { createId.current ??= crypto.randomUUID(); const data = await api("/api/circles", { action: "create", id: createId.current, name }); createId.current = null; setName(""); await refresh(); await open(data.id); }); }}><label htmlFor="circle-name">Nom du cercle</label><input id="circle-name" maxLength={40} value={name} disabled={busy} onChange={event => { createId.current = null; setName(event.target.value); }} /><button className="primary-button" disabled={busy || !name.trim()}>Créer un cercle</button></form>
      <form onSubmit={event => { event.preventDefault(); void perform(async () => { const data = await api("/api/circles", { action: "join", token: token.trim() }); setToken(""); await refresh(); await open(data.circle_id); }); }}><label htmlFor="circle-token">Code d’invitation</label><input id="circle-token" autoComplete="off" value={token} disabled={busy} onChange={event => setToken(event.target.value)} /><button className="text-action" disabled={busy || !token.trim()}>Rejoindre explicitement</button></form></section>
      {details && <section className="collection-picker laboratory-card"><h2>{details.circle.name}</h2><p>20 membres maximum. Une exclusion retire l’accès au cercle et à ses parties.</p><ul>{details.members.map(member => <li key={member.id}>{member.name}{details.circle.owner_id === session.guest?.id && member.id !== session.guest.id && <details><summary>Gérer ce membre</summary><button disabled={busy} onClick={() => void perform(async () => { await api("/api/circles", { action: "exclude", id: details.circle.id, guest: member.id }); await open(details.circle.id); })}>Confirmer l’exclusion</button></details>}</li>)}</ul>
      {details.circle.owner_id === session.guest.id && <><button className="text-action" disabled={busy} onClick={() => void perform(async () => { inviteToken.current ??= [...crypto.getRandomValues(new Uint8Array(32))].map(v => v.toString(16).padStart(2, "0")).join(""); await api("/api/circles", { action: "invite", id: details.circle.id, token: inviteToken.current }); setLink(`${location.origin}/cercles#invitation=${inviteToken.current}`); })}>Créer un lien d’invitation</button>{link && <label>Lien privé, valable 7 jours<input readOnly value={link} onFocus={event => event.target.select()} /></label>}<details><summary>Révoquer les invitations</summary><button disabled={busy} onClick={() => void perform(async () => { await api("/api/circles", { action: "revoke", id: details.circle.id }); setLink(""); inviteToken.current = null; })}>Confirmer la révocation de tous les liens</button></details></>}
      <button className="primary-button" disabled={busy} onClick={() => void perform(async () => { const data = await api("/api/circles", { action: "weekly", id: details.circle.id }); await open(details.circle.id, data.id); })}>Ouvrir le défi de cette semaine</button>
      <h3>Défis et archives</h3>{details.challenges.map(challenge => <div key={challenge.id}><span>Semaine du {challenge.week}</span><button className="text-action" disabled={busy} onClick={() => void perform(async () => { const data = await api("/api/circles", { action: "enter", id: details.circle.id, challenge: challenge.id }); location.assign(`/espace?game=${encodeURIComponent(data.game)}`); })}>Jouer ou reprendre</button><button className="text-action" disabled={busy} onClick={() => void perform(() => open(details.circle.id, challenge.id))}>Voir les résultats</button></div>)}
      <p>Réussites d’abord, puis nombre d’essais ; sinon meilleur rang. Égalités conservées. Aucun mot adverse n’est montré.</p><ul>{details.results.map((result, index) => <li key={index}>{result.name} : {result.state === "won" ? `trouvé en ${result.revision} essais` : result.best_rank ? `meilleur rang ${result.best_rank}` : "pas encore de proposition"}</li>)}</ul></section>}
    </>}{busy && <p role="status">Chargement…</p>}{error && <p role="alert">{error}</p>}</main>;
}
