"use client";
import { useEffect, useRef, useState } from "react";
type View = { id: string; state: string; deadline: number | null; role: string; forfeiter: string | null; decisions: number[] | null; guesses: Array<{ round: number; word: string; ordinal: number; temperature: number; rank: number; found: number }> };
export default function Duels() {
  const [session, setSession] = useState<{ guest: { id: string; name: string } | null; csrf?: string }>({ guest: null });
  const [view, setView] = useState<View | null>(null); const [duels, setDuels] = useState<Array<{ id: string; state: string }>>([]);
  const [token, setToken] = useState(""); const [link, setLink] = useState(""); const [round, setRound] = useState(0); const [word, setWord] = useState("");
  const [guestName, setGuestName] = useState("");
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const lock = useRef(false); const inputRevision = useRef(0);
  const creation = useRef<{ id: string; token: string } | null>(null);
  const pending = useRef<{ id: string; round: number; revision: number; requestId: string; word: string } | null>(null);
  async function api(path: string, body?: unknown) { const response = await fetch(path, body ? { method: "POST", headers: { "Content-Type": "application/json", "X-Braise-CSRF": session.csrf ?? "" }, body: JSON.stringify(body) } : { cache: "no-store" }); const data = await response.json() as View & { guest: { id: string; name: string } | null; csrf?: string; duels: Array<{ id: string; state: string }>; error?: string }; if (!response.ok) throw new Error(data.error ?? "Service indisponible."); return data; }
  async function perform(action: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Service indisponible."); } finally { lock.current = false; setBusy(false); } }
  async function refresh() { setDuels((await api("/api/duels")).duels); }
  async function create() { creation.current ??= { id: crypto.randomUUID(), token: [...crypto.getRandomValues(new Uint8Array(32))].map(v => v.toString(16).padStart(2, "0")).join("") }; const data = await api("/api/duels", { action: "create", ...creation.current }); setView(data); setLink(`${location.origin}/duels#invitation=${creation.current.token}`); creation.current = null; pending.current = null; setRound(0); setWord(""); await refresh(); }
  useEffect(() => { const value = new URLSearchParams(location.hash.slice(1)).get("invitation"); if (value) { setToken(value); history.replaceState(null, "", location.pathname); } void perform(async () => { const data = await api("/api/session"); setSession(data); if (data.guest) await refresh(); });
  // Restoring a page never accepts an invitation.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const guesses = view?.guesses.filter(guess => guess.round === round) ?? [];
  const won = guesses.some(guess => guess.found === 1);
  return <main className="main-shell laboratory-shell"><a className="text-action" href="/">← Braise</a><div className="page-heading"><h1>Les duels<span>.</span></h1></div><p>Trois mots distincts, les mêmes pour vous deux. 48 heures après acceptation, 30 mots valides distincts par manche, sans indice. Les propositions adverses restent privées.</p>
    {!session.guest ? <section className="collection-picker laboratory-card"><form onSubmit={event => { event.preventDefault(); void perform(async () => { setSession(await api("/api/session", { name: guestName })); await refresh(); }); }}><label htmlFor="duel-guest">Votre pseudonyme</label><input id="duel-guest" maxLength={24} value={guestName} disabled={busy} onChange={event => setGuestName(event.target.value)} /><button className="primary-button" disabled={busy || !guestName.trim()}>Créer mon identité et conserver cette invitation</button></form><p>Pour retrouver une identité existante, utilisez Votre espace puis rouvrez le lien d’invitation.</p><a href="/espace">Retrouver mon identité</a></section> : <section className="collection-picker laboratory-card"><button className="primary-button" disabled={busy} onClick={() => void perform(create)}>Inviter à un nouveau duel</button>{link && <label>Lien privé, invitation valable 7 jours<input readOnly value={link} onFocus={event => event.target.select()} /></label>}
      <form onSubmit={event => { event.preventDefault(); void perform(async () => { setView(await api("/api/duels", { action: "accept", token: token.trim() })); setToken(""); setLink(""); setRound(0); pending.current = null; await refresh(); }); }}><label htmlFor="duel-token">Code d’invitation</label><input id="duel-token" value={token} disabled={busy} autoComplete="off" onChange={event => setToken(event.target.value)} /><button className="text-action" disabled={busy || !token.trim()}>Accepter et démarrer les 48 heures</button></form>
      <details><summary>Mes 50 derniers duels</summary>{duels.map(duel => <button className="text-action" key={duel.id} disabled={busy} onClick={() => void perform(async () => { setView(await api(`/api/duels?id=${duel.id}`)); pending.current = null; setLink(""); setRound(0); setWord(""); })}>Ouvrir le duel {duel.id.slice(0, 8)}</button>)}</details>
      {view && <><h2>{view.state === "pending" ? "En attente d’un adversaire" : view.state === "finished" ? "Bilan du duel" : view.state === "expired" ? "Invitation expirée, aucun résultat" : view.state === "cancelled" ? "Invitation annulée" : "À vous de jouer"}</h2>{view.deadline && <p>Échéance : {new Date(view.deadline).toLocaleString("fr-FR", { timeZone: "Europe/Paris" })} (Paris).</p>}<button className="text-action" disabled={busy} onClick={() => void perform(async () => { setView(await api(`/api/duels?id=${view.id}`)); pending.current = null; })}>Actualiser</button>
      {(view.state === "active" || view.state === "finished") && <><div role="group" aria-label="Choisir la manche">{[0, 1, 2].map(index => <button key={index} className="text-action" disabled={busy} aria-pressed={round === index} onClick={() => { setRound(index); setWord(""); pending.current = null; }}>Manche {index + 1}</button>)}</div><p>{won ? "Mot trouvé ✓" : `${guesses.length}/30 propositions`}</p>
      {view.state === "active" && !won && guesses.length < 30 && <form className="guess-form" onSubmit={event => { event.preventDefault(); const revision = inputRevision.current; void perform(async () => { const old = pending.current; const request = old && old.id === view.id && old.round === round && old.word === word.trim() ? old : { id: view.id, round, revision: guesses.length, requestId: crypto.randomUUID(), word: word.trim() }; pending.current = request; setView(await api("/api/duels", { action: "guess", ...request })); pending.current = null; if (revision === inputRevision.current) setWord(""); }); }}><label className="sr-only" htmlFor="duel-word">Votre mot</label><input id="duel-word" maxLength={50} value={word} onChange={event => { inputRevision.current++; setWord(event.target.value); }} /><button className="guess-button" disabled={busy || !word.trim()}>→</button></form>}
      <ul>{[...guesses].reverse().map(guess => <li key={guess.ordinal}>{guess.word} · {guess.temperature.toFixed(1)}° · rang {guess.rank}</li>)}</ul></>}
      {view.state === "finished" && <><p>{view.forfeiter ? view.forfeiter === view.role ? "Vous avez abandonné le duel." : "Votre adversaire a abandonné le duel." : "Trouver prime ; entre réussites, moins d’essais ; sinon meilleur rang. Les égalités sont conservées."}</p>{!view.forfeiter && <ol>{view.decisions?.map((decision, index) => <li key={index}>{decision === 0 ? "Égalité" : (decision === -1) === (view.role === "host") ? "Manche remportée" : "Manche remportée par l’adversaire"}</li>)}</ol>}<button className="primary-button" disabled={busy} onClick={() => void perform(create)}>Proposer une revanche distincte</button></>}
      {(view.state === "pending" || view.state === "active") && <details><summary>{view.state === "pending" ? "Annuler l’invitation" : "Abandonner le duel"}</summary><button disabled={busy} onClick={() => void perform(async () => { setView(await api("/api/duels", { action: view.state === "pending" ? "cancel" : "forfeit", id: view.id })); setLink(""); })}>Confirmer</button></details>}</>}
    </section>}{busy && <p role="status">Chargement…</p>}{error && <p role="alert">{error}</p>}<p>Le Site reste privé. Aucun classement global ni adversaire fictif.</p></main>;
}
