"use client";
import { useEffect, useRef, useState } from "react";
type Draft = { id: string; title: string; entries: string[]; revision: number; editions?: Array<{ id: string; revision: number; state: string }> };
type Progress = { id: string; title: string; length: number; completed: number; game: string | null };
type Data = Draft & Progress & { guest: { id: string; name: string } | null; csrf?: string; drafts: Draft[]; catalogue: Array<{ id: string; label: string }>; titles: string[]; error?: string; state: string };
export default function Studio() {
  const [session, setSession] = useState<{ guest: { id: string; name: string } | null; csrf?: string }>({ guest: null });
  const [data, setData] = useState<{ drafts: Draft[]; catalogue: Array<{ id: string; label: string }>; titles: string[] }>({ drafts: [], catalogue: [], titles: [] });
  const [draft, setDraft] = useState<Draft | null>(null); const [progress, setProgress] = useState<Progress | null>(null);
  const [edition, setEdition] = useState(""); const [guestName, setGuestName] = useState(""); const [link, setLink] = useState("");
  const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [dirty, setDirty] = useState(false); const lock = useRef(false);
  async function api(path: string, body?: unknown) { const response = await fetch(path, body ? { method: "POST", headers: { "Content-Type": "application/json", "X-Braise-CSRF": session.csrf ?? "" }, body: JSON.stringify(body) } : { cache: "no-store" }); const result = await response.json() as Data; if (!response.ok) throw new Error(result.error ?? "Service indisponible."); return result; }
  async function perform(action: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Service indisponible."); } finally { lock.current = false; setBusy(false); } }
  async function refresh() { setData(await api("/api/studio")); }
  useEffect(() => { const selected = new URLSearchParams(location.search).get("edition") ?? ""; setEdition(selected); void perform(async () => { const s = await api("/api/session"); setSession(s); if (s.guest) { if (selected) setProgress(await api(`/api/studio?edition=${encodeURIComponent(selected)}`)); else await refresh(); } });
  // Restore only; visiting a shared edition creates no game.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { if (!dirty) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", guard); return () => window.removeEventListener("beforeunload", guard); }, [dirty]);
  function change(entries: string[]) { if (draft) { setDraft({ ...draft, entries }); setDirty(true); setLink(""); } }
  return <main className="main-shell laboratory-shell"><a className="text-action" href="/">← Braise</a><div className="page-heading"><h1>{edition ? "Une création Braise" : "Le studio"}<span>.</span></h1></div><p>Des énigmes du catalogue éditorial, une édition stable, aucun changement au mot quotidien. Les liens restent privés.</p>
    {!session.guest ? <section className="collection-picker laboratory-card"><form onSubmit={event => { event.preventDefault(); void perform(async () => { setSession(await api("/api/session", { name: guestName })); if (edition) setProgress(await api(`/api/studio?edition=${encodeURIComponent(edition)}`)); else await refresh(); }); }}><label htmlFor="studio-guest">Pseudonyme</label><input id="studio-guest" maxLength={24} value={guestName} disabled={busy} onChange={event => setGuestName(event.target.value)} /><button className="primary-button" disabled={busy || !guestName.trim()}>Créer mon identité</button></form><a href="/espace">Retrouver une identité existante</a></section> : edition ? <section className="collection-picker laboratory-card">{progress && <><h2>{progress.title}</h2><p>{progress.completed}/{progress.length} étapes terminées</p>{progress.completed < progress.length ? <button className="primary-button" disabled={busy} onClick={() => void perform(async () => { const result = await api("/api/studio", { action: "enter", id: edition }); location.assign(`/espace?game=${encodeURIComponent(result.game!)}&edition=${edition}`); })}>Jouer la prochaine étape</button> : <p>Création terminée ✓</p>}</>}</section> : <section className="collection-picker laboratory-card"><h2>Mes brouillons</h2>{data.drafts.map(item => <button className="text-action" disabled={busy || dirty} key={item.id} onClick={() => void perform(async () => { setDraft(await api(`/api/studio?id=${item.id}`)); setLink(""); })}>{item.title} · révision {item.revision}</button>)}<button className="primary-button" disabled={busy || dirty || !data.titles.length} onClick={() => { setDraft({ id: crypto.randomUUID(), title: data.titles[0], entries: [], revision: -1 }); setDirty(true); setLink(""); }}>Nouveau brouillon</button>
      {draft && <><label htmlFor="studio-title">Titre approuvé</label><select id="studio-title" disabled={busy} value={draft.title} onChange={event => { setDraft({ ...draft, title: event.target.value }); setDirty(true); setLink(""); }}>{data.titles.map(title => <option key={title}>{title}</option>)}</select><label htmlFor="studio-choice">Ajouter une énigme</label><select id="studio-choice" value="" disabled={busy || draft.entries.length >= 12} onChange={event => { if (event.target.value) change([...draft.entries, event.target.value]); }}><option value="">Choisir dans le catalogue</option>{data.catalogue.filter(item => !draft.entries.includes(item.id)).map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select>
      <ol>{draft.entries.map((entry, index) => <li key={entry}>{data.catalogue.find(item => item.id === entry)?.label}<button className="text-action" disabled={busy || index === 0} aria-label={`Monter l’énigme ${index + 1}`} onClick={() => { const next = [...draft.entries]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; change(next); }}>↑</button><button className="text-action" disabled={busy || index === draft.entries.length - 1} aria-label={`Descendre l’énigme ${index + 1}`} onClick={() => { const next = [...draft.entries]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; change(next); }}>↓</button><button className="text-action" disabled={busy} aria-label={`Retirer l’énigme ${index + 1}`} onClick={() => change(draft.entries.filter((_, i) => i !== index))}>Retirer</button></li>)}</ol><p>Aperçu : {draft.title}, {draft.entries.length} étapes dans cet ordre. Le participant ne reçoit que l’étape débloquée.</p>
      <button className="primary-button" disabled={busy || !draft.entries.length || !dirty} onClick={() => void perform(async () => { setDraft(await api("/api/studio", { action: "save", ...draft })); setDirty(false); await refresh(); })}>Enregistrer le brouillon</button>{dirty && <details><summary>Abandonner mes modifications non enregistrées</summary><button disabled={busy} onClick={() => void perform(async () => { if (draft.revision >= 0) setDraft(await api(`/api/studio?id=${draft.id}`)); else setDraft(null); setDirty(false); })}>Confirmer le rechargement</button></details>}
      <button className="text-action" disabled={busy || dirty || draft.revision < 0} onClick={() => void perform(async () => { const result = await api("/api/studio", { action: "publish", id: draft.id, revision: draft.revision }); if (result.state !== "active") throw new Error("Cette révision a été retirée. Enregistrez une nouvelle révision pour republier."); setLink(`${location.origin}/studio?edition=${result.id}`); setDraft(await api(`/api/studio?id=${draft.id}`)); })}>Publier une édition immuable</button>{link && <label>Lien de l’édition<input readOnly value={link} onFocus={event => event.target.select()} /></label>}
      {draft.editions?.map(item => <div key={item.id}>Édition {item.revision} · {item.state === "active" ? "Disponible" : "Retirée"}{item.state === "active" && <details><summary>Retirer cette édition</summary><button disabled={busy} onClick={() => void perform(async () => { await api("/api/studio", { action: "withdraw", id: item.id }); const refreshed = await api(`/api/studio?id=${draft.id}`); setDraft(current => current ? { ...current, editions: refreshed.editions } : null); setLink(""); })}>Confirmer le retrait</button></details>}</div>)}</>}
    </section>}{busy && <p role="status">Chargement…</p>}{error && <p role="alert">{error}</p>}</main>;
}
